---
- name: Add domain admins
  win_domain_user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
    groups:
      - Domain Admins
      - Domain Users
    upn: "{{ item }}@{{ domain_name }}"
  loop:
    - Agustus
    - Cato
    - Sulla
    - Lucius
    - Favonius
    - Julius
    - Marcus
    - Vinicius
    - Octavius

- name: Add domain users
  win_domain_user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
    groups:
      - Domain Users
    upn: "{{ item }}@{{ domain_name }}"
  loop:
    - Maximus
    - Pompey
    - Cicero
    - Plato
    - Socrates
    - Aristotle
    - Epicurus
    - Plutarch
    - Jeffery
    - Jeff
    - Jeofery
    - Matt
    - Martha