---
# Deploy domain controllers
- hosts: alexander
  roles:
    - alexander-deployment
    #- alexander-makedomain-deploy
    #- alexander-addusers-deploy

# Deploy file servers
- hosts: julius
  roles:
    - julius-deployment
    #- julius-smbftp-deploy

# Deploy public web server
- hosts: bonaparte
  roles:
    - bonaparte-deployment
    #- bonaparte-iis-deploy

# Deploy mail server
- hosts: xerxes
  roles:
    - xerxes-deployment
    #- xerxes-mail-deploy

# Apply Windows standards
- hosts: Windows
  roles:
    - windows-standards
    #- windows-localusers-deploy
    #- windows-joindomain-deploy
    #- windows-mapdrive-deploy

# Install docker host
- hosts: churchill
  become: yes
  roles:
    - churchill-deployment
    #- churchill-docker-deploy

# Install Graylog
- hosts: leonidas
  become: yes
  roles:
    - leonidas-deployment
    #- Leonidas

# Install LAMP app
- hosts: attila 
  become: yes
  roles:
    - attila-deployment
    #- attila-webapp-deploy

# Install OpenVPN server
- hosts: ashoka
  become: yes
  roles:
    - ashoka-deployment
    #- ashoka-openvpn-deploy

# Install public DNS server
- hosts: gandhi
  become: yes
  roles:
    - gandhi-deployment
    #- gandhi-dns-deploy
    #- gandhi-http-deploy

# Install GitLab
- hosts: ataturk
  become: yes
  roles:
    - ataturk-deployment
    #- ataturk

# Apply Linux standards
- hosts: Linux
  become: yes
  roles:
    - linux-standards
    #- linux-hostname-deploy
    #- linux-addusers-deploy
    #- linux-addadmin-deploy
  