---
# Deploy domain controllers
- hosts: alexander
  roles:
    - alexander-deployment

# Deploy file servers
- hosts: julius
  roles:
    - julius-deployment

# Deploy public web server
- hosts: bonaparte
  roles:
    - bonaparte-deployment

# Deploy mail server
- hosts: xerxes
  roles:
    - xerxes-deployment

# Apply Windows standards
- hosts: Windows
  roles:
    - windows-standards

# Install docker host
- hosts: churchill
  become: yes
  roles:
    - churchill-deployment

# Install Graylog
- hosts: leonidas
  become: yes
  roles:
    - leonidas-deployment

# Install LAMP app
- hosts: attila 
  become: yes
  roles:
    - attila-deployment
    #- attila-webapp-deploy

# Install OpenVPN server
- hosts: ashoka
  become: yes
  roles:
    - ashoka-deployment
    #- ashoka-openvpn-deploy

# Install public DNS server
- hosts: gandhi
  become: yes
  roles:
    - gandhi-deployment
    #- gandhi-dns-deploy
    #- gandhi-http-deploy

# Install GitLab
- hosts: ataturk
  become: yes
  roles:
    - ataturk-deployment
    #- ataturk

# Apply Linux standards
- hosts: Linux
  become: yes
  roles:
    - linux-standards
    #- linux-hostname-deploy
    #- linux-addusers-deploy
    #- linux-addadmin-deploy
  