---
# tasks file for linux-addusers-deploy
#- name: Include user list
#  include_vars: "local_accounts.yml"



- name: Add user accounts - Linux
  user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
  with_items: "{{ accounts }}"
  when: ansible_system == "Linux"

- name: Add local admin accounts - Linux
  user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
    groups: 
        - "sudo"
  with_items: "{{ admin_accounts }}"
  when: ansible_os_family == "Debian"

- name: Add local admin accounts
  user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
    groups: 
      - "wheel"
  with_items: "{{ admin_accounts }}"
  when: ansible_os_family == "RedHat"

- name: Add local admin accounts
  user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
    groups: 
      - "sudoers"
  with_items: "{{ admin_accounts }}"
  when: ansible_os_family == "BSD"


# Cucumber Linux nonsense
- name: Handle cucumber Linux
  shell: "/bin/cat /etc/*rel* | /bin/grep DISTRIB_ID"
  register: command_output

- name: Create wheel group - Cucumber
  group:
    name: wheel
    state: present
  when: command_output.stdout.find('ucumber') != -1 
  become: yes

- name: Add wheel group to sudoers - Cucumber
  lineinfile:
    path: /etc/sudoers
    line: "%wheel ALL=(ALL) ALL"
  when: command_output.stdout.find('ucumber') != -1 
  become: yes

- name: Add local admin accounts
  user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
    groups: 
      - "wheel"
  with_items: "{{ admin_accounts }}"
  when: command_output.stdout.find('ucumber') != -1 
  become: yes

- name: Add accounts accounts
  user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    state: present
  with_items: "{{ admin_accounts }}"
  when: command_output.stdout.find('ucumber') != -1 
  become: yes
