---

# Whats a yum
- name: Yum update
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == 'CentOS'

- name: Yum install stuff
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release

# This will already be there as the only thing running redhat is the ossec server
- name: "Install atomicorp repo"
  yum:
    name: "https://www.atomicorp.com/channels/atomic/centos/7/x86_64/RPMS/atomic-release-1.0-21.el7.art.noarch.rpm"
    state: present

- name: Install ossec-hids-agent
  package:
    name: "ossec-hids-agent"
  when: "'.deb' not in ossec_agent_package_name"

- name: Set ossec deploy facts for RedHat
  set_fact:
    ossec_agent_config_filename: ossec-agent.conf
    ossec_init_name: ossec-hids

# Need to do this not this way
- name: Installing the ossec-agent.conf
  template:
    src: ossec_agent.conf
    dest: /var/ossec/etc/{{ ossec_agent_config_filename }}
    owner: root
    group: root
    mode: 0644
  notify: restart ossec-agent
  tags:
    - init
    - config

- name: "Check if client.keys exists"
  stat:
    path: /var/ossec/etc/client.keys
  register: check_keys
  tags:
    - config

- name: "Check if client.keys exists on ossec-server"
  stat:
    path: /var/ossec/etc/client.keys
  when: ossec_managed_server
  delegate_to: "{{ ossec_server_name }}"
  register: check_server_keys
  tags:
    - config

- name: "Starting auth daemon on server {{ ossec_server_name }}"
  service:
    name: ossec-authd
    state: started
  when: ossec_managed_server and not check_keys.stat.exists and ossec_server_name|default("") != ""
  delegate_to: "{{ ossec_server_name }}"
  run_once: true
  tags:
    - config

- name: "register client"
  shell: "/var/ossec/bin/agent-auth -m {{ ossec_server_ip|default(ossec_server_fqdn) }} -p 1515 -A '{{ ossec_agent_name|default(ansible_hostname) }}'"
  args:
    creates: /var/ossec/etc/client.keys
  tags:
    - config
    - skip_ansible_lint

- name: Set permissions on client.keys file
  file:
    dest: /var/ossec/etc/client.keys
    mode: 0640

- name: "kill the auth-daemon on server {{ ossec_server_name }}"
  service:
    name: ossec-authd
    state: stopped
  delegate_to: "{{ ossec_server_name }}"
  when: ossec_managed_server and not check_keys.stat.exists and ossec_server_name|default("") != ""
  run_once: true
  tags:
    - config

- name: "Restart ossec-remoted on server. If this is the first agent added it will not be running."
  shell: /var/ossec/bin/ossec-control restart
  delegate_to: "{{ ossec_server_name }}"
  when: ossec_managed_server and not check_server_keys.stat.exists and ossec_server_name|default("") != ""
  run_once: true
  tags:
    - skip_ansible_lint

- name: "Start ossec-agent if not already running"
  service:
    name: "{{ ossec_init_name }}"
    state: started
    enabled: yes