---
# tasks file for bonaparte-iis-deploy

- name: ensure the iis modules are installed
  win_feature:
    name:
      - Web-Default-Doc
      - Web-Dir-Browsing
      - Web-Http-Errors
      - Web-Static-Content
      - Web-Mgmt-Console
    state: present
  register: iis_result

- name: restart if required
  when: iis_result.reboot_required
  win_reboot:

- name: copy ssl binding script over
  win_copy:
    src: files/ssl_binding.ps1
    dest: C:\ssl_binding.ps1

- name: run the ssl_binding script to generate an ssl binding for iis
  win_command: powershell.exe -executionpolicy bypass C:\ssl_binding.ps1

- name: restart the web service
  win_service:
    name: W3SVC
    state: restarted
    start_mode: auto
