---
- iptables:
    chain: INPUT
    policy: ACCEPT

- iptables:
    chain: FORWARD
    policy: ACCEPT

- iptables:
    chain: OUTPUT
    policy: ACCEPT

- iptables:
    flush: yes

- lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PermitRootLogin'
    line: 'PermitRootLogin yes'

- lineinfile:
    path: /etc/sysconfig/network/config
    regexp: 'NETCONFIG_DNS_STATIC_SERVERS'
    line: "NETCONFIG_DNS_STATIC_SERVERS=\"{{ '10.' + play_hosts.index(inventory_hostname) | string + '.1.1' }}\""

- lineinfile:
    path: /etc/sysconfig/network/ifcfg-eth0
    regexp: "BOOTPROTO="
    line: "BOOTPROTO='static'"

- lineinfile:
    path: /etc/sysconfig/network/ifcfg-eth0
    regexp: "IPADDR="
    line: IPADDR='{{ "10." + play_hosts.index(inventory_hostname) | string + ".1.3/24" }}'

- lineinfile:
    path: /etc/sysconfig/network/ifcfg-eth0
    regexp: "DHCLIENT_SET_DEFAULT_ROUTE"
    state: absent

- name: ensure file exists
  copy:
    content: ""
    dest: /etc/sysconfig/network/routes
    force: yes
    group: root
    owner: root
    mode: 0644

- lineinfile:
    path: /etc/sysconfig/network/routes
    line: "{{ '10.' + play_hosts.index(inventory_hostname) | string + '.1.254 --' }}"
  notify: ataturk-networking
