---
- name: Set DNS to the AD server
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses: "10.2.{{ team_number }}.1"

- name: Join the domain
  win_domain_membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_password: "{{ password }}"
    domain_admin_user: "{{ username }}" 
    state: domain
  register: domain_result

- name: Reboot after joining domain
  when: domain_result.reboot_required
  win_reboot:
