---
docker_ce_ubuntu_prerequisite_packages:
  - apt-transport-https
  - ca-certificate
  - curl
  - gnupg-agent
  - software-properties-common
docker_ce_ubuntu_packages:
  - docker-ce
  - docker-ce-cli