---
# tasks file for xerses-mail-deploy
# Author: Micah Martin
# Modified by Connor Shade for ISTS17
# Copy the configure script to the server for
- name: Copying configure script
  win_copy:
    src: files/Setup-hMail.ps1
    dest: C:\Setup-hMail.ps1

- name: copy hmail over if required 
  win_copy:
    src: ./files/hmailserver.exe
    dest: C:\hmailserver.exe

- name: making sure hmailserver is installed
  win_package:
    path: C:\hmailserver.exe
    state: present
    product_id: hMailServer_is1
    arguments: /verysilent
  register: mail_result

- name: restarting if needed
  when: mail_result.reboot_required == true
  win_reboot:

- name: Run script
  script: Setup-hMail.ps1 -domainName "{{ domainname }}" -ipAddr "10.{{ team_number }}.0.6"
