---
# Domain name for the hMail server
hmail_domain_name: "{{ domain_name }}"

# New users to add to the mail server
hmail_users:
  - jeff
  - martha

# Default password for all the user account
hmail_password: "{{ password }}"
