- name: Verify PAN is reachable
  panos_check:
    ip_address: "10.0.200.{{ team_number }}"
    password: "admin"
  register: auth_check
  ignore_errors: yes

- name: Copy config to /tmp
  template:
    src: ../templates/config.xml
    dest: /tmp/config.xml
  when: auth_check is not failed

- name: Upload PAN config
  panos_import:
    ip_address: "10.0.200.{{ team_number }}"
    password: "admin"
    file: /tmp/config.xml
    category: "configuration"
    validate_certs: no
  environment:
    PYTHONHTTPSVERIFY: 0
  register: upload_result
  when: auth_check is not failed

- name: Load configuration
  panos_loadcfg:
    ip_address: "10.0.200.{{ team_number }}"
    password: "admin"
    file: "{{upload_result.filename}}"
  environment:
    PYTHONHTTPSVERIFY: 0
  register: load_result
  when: upload_result is not failed

- name: Reboot PAN
  panos_restart:
    ip_address: "10.0.200.{{ team_number }}"
    password: "admin"
  environment:
    PYTHONHTTPSVERIFY: 0
  when: load_result is not failed

- name: Delete config from /tmp
  file:
    path: /tmp/config.xml
    state: absent
  when: load_result is not failed
