---
# tasks file for gandhi-dns-deploy

- name: Install MariaDB server
  pkgng:
    cached: no
    name: mariadb103-server-10.3.11
    state: present

- name: Add MariaDB server to /etc/rc.conf
  shell: grep mysql_enable /etc/rc.conf || echo 'mysql_enable=YES' >> /etc/rc.conf

- name: Enable MariaDB server
  service:
    name: mysql-server
    state: started

- name: Copy pdns.sql
  copy:
    src: pdns.sql
    dest: /pdns.sql

- name: Import pdns.sql
  shell: mysql -u root < /pdns.sql

- name: Remove pdns.sql from remote host
  file:
    path: /pdns.sql
    state: absent

- name: Install PowerDNS
  pkgng:
    cached: no
    name: dns/powerdns
    state: present

- name: Add PowerDNS to /etc/rc.conf
  shell: grep pdns_enable /etc/rc.conf || echo 'pdns_enable="YES"' >> /etc/rc.conf

- name: Configure PowerDNS
  copy:
    src: pdns.conf
    dest: /usr/local/etc/pdns/pdns.conf

- name: Enable PowerDNS
  service:
    name: pdns
    state: started