---
# vars file for OssecGraylog
ossec_hostname: leonidas
ossec_fqdn: '{{ ossec_hostname }}.team{{ team_number }}.{{ internal_base_domain }}'

# Graylog 
graylog_admin_password: '{{ default_password }}'

# Timezone
timezone: America/New_York

# Ossec 
ossec_server_atomic_release: 1.0-21

syslog_port: 1516
# Correct IP
ossec_ip: '10.2.{{ team_number }}.4'