---
- name: Download RPM
  yum:
    name: https://packages.graylog2.org/repo/packages/graylog-2.3-repository_latest.rpm
    state: present

- name: Install/Setup Graylog
  package:
    name:
      - graylog-server
      - pwgen
    state: present

- name: Covert password to sha256 hash
  shell: "echo -n {{ graylog_admin_password }} | sha256sum | awk '{print $1}'"
  register: pass_contents

#- name: Set admin password
#  lineinfile:
#    path: /etc/graylog/server/server.conf
#    regexp: '^root_password_sha2 ='
#    line: "root_password_sha2 = {{ pass_contents.stdout }}"

- name: Generate secret key
  shell: "pwgen -s 96 1"
  register: secret_key_content

#- name: Set secret key
#  shell: sed -i -e "s/password_secret =.*/password_secret = {{ secret_key_content.stdout }}/" /etc/graylog/server/server.conf

- name: Drop me config in
  template:
    src: server.conf
    dest: /etc/graylog/server/server.conf

- name: Start and Enable Graylog service
  service:
    name: graylog-server
    state: restarted
    enabled: yes

- name: "Wait for my boi to come up"
  uri:
    url: "https://{{ ossec_fqdn }}"
    status_code: 200
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 60
  delay: 5

- name: Get node id
  uri:
      url: https://{{ ossec_fqdn }}/api/cluster
      method: GET
      validate_certs: no
      user: admin
      password: "{{ graylog_admin_password }}"
  register: nodeid

- name: Add Syslog input
  uri:
      url: https://{{ ossec_fqdn }}/api/system/inputs
      method: POST
      status_code: 201
      validate_certs: no
      body_format: json
      user: admin
      password: "{{ graylog_admin_password }}" 
      body: 
        title: "Ossec syslog"
        type: "org.graylog2.inputs.syslog.udp.SyslogUDPInput"
        global: false
        configuration: 
          port: 1516
          recv_buffer_size: 262144
          tls_enable: false, 
          bind_address: "0.0.0.0"
        node: "{{ nodeid.x_graylog_node_id }}"
      headers:
        Content-Type: "application/json"
